# Generated by Django 4.2.3 on 2023-07-19 16:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0006_event_location_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('facebook', models.CharField(blank=True, default='https://facebook.com', max_length=254, null=True)),
                ('twitter', models.CharField(blank=True, default='https://twitter.com', max_length=254, null=True)),
                ('instagram', models.CharField(blank=True, default='https://instagram.com', max_length=254, null=True)),
                ('linkedin', models.CharField(blank=True, default='https://linkedin.com', max_length=254, null=True)),
                ('groups', models.ManyToManyField(related_name='portfolio_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='portfolio_user_user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'portfolio_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bronchure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='bronchures')),
            ],
            options={
                'verbose_name': 'Bronchure',
                'verbose_name_plural': 'Bronchures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=254, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('type', models.CharField(blank=True, default='message', max_length=254, null=True)),
            ],
            options={
                'db_table': 'contact_message',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('testifier', models.CharField(max_length=254)),
                ('testifier_role', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('slug', models.CharField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(upload_to='testimonials')),
            ],
            options={
                'db_table': 'testimonial',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('id_doc', models.ImageField(blank=True, null=True, upload_to='registrations/id_docs')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='registrations/passports')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.course')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=254)),
                ('image', models.ImageField(null=True, upload_to='about')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'about',
            },
        ),
    ]
