# Generated by Django 4.2.3 on 2023-07-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_alter_adminuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='adminportal.adminuser'),
        ),
    ]
