# Generated by Django 4.2.3 on 2023-07-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('adminportal', '0003_alter_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='groups',
            field=models.ManyToManyField(related_name='admin_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='admin_user_permissions', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
