# Generated by Django 4.2.3 on 2023-07-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_course_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='start_date',
            new_name='start_on',
        ),
    ]
