# Generated by Django 4.2.3 on 2023-07-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_blog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='Boltech Institute', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
